# Generated by Django 4.0.3 on 2026-05-14 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('peyment', '0001_initial'),
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peyment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peyment_customer', to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AddField(
            model_name='peyment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peyment_order', to='order.order', verbose_name='سفارش'),
        ),
    ]
