# Generated by Django 4.0.3 on 2026-05-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peyment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peyment',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام دارنده کارت'),
        ),
        migrations.AddField(
            model_name='peyment',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت مبدا'),
        ),
        migrations.AddField(
            model_name='peyment',
            name='payment_method',
            field=models.CharField(choices=[('card_to_card', 'کارت به کارت'), ('online', 'درگاه پرداخت آنلاین')], default='online', max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AddField(
            model_name='peyment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/%d/', verbose_name='تصویر رسید'),
        ),
        migrations.AddField(
            model_name='peyment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره پیگیری'),
        ),
    ]
