# Generated by Django 4.0.3 on 2026-06-07 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_order_type_order_printing_and_more'),
        ('peyment', '0003_peyment_card_holder_name_peyment_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peyment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peyment_order', to='order.order', verbose_name='سفارش'),
        ),
    ]
