# Generated by Django 4.0.3 on 2026-06-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peyment', '0004_alter_peyment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='peyment',
            name='amount_toman',
            field=models.IntegerField(blank=True, null=True, verbose_name='مبلغ پرداخت (تومان)'),
        ),
    ]
