# Generated by Django 4.0.3 on 2026-06-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peyment', '0005_peyment_amount_toman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peyment',
            name='amount_toman',
        ),
    ]
