# Generated by Django 5.2.15 on 2026-09-21 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreOrAccept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countIgnore', models.PositiveIntegerField(default=0, verbose_name='تعداد رد شدن')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='دلیل')),
                ('is_accept', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('is_ignore', models.BooleanField(default=False, verbose_name='رد شده')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'بررسی رسید',
                'verbose_name_plural': 'بررسی\u200cهای رسید',
            },
        ),
        migrations.CreateModel(
            name='Peyment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peyment_type', models.CharField(choices=[('card', 'کارت به کارت'), ('gateway', 'درگاه پرداخت')], default='card', max_length=20, verbose_name='نوع پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('amount', models.IntegerField(verbose_name='مبلغ پرداخت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات پرداخت')),
                ('isFinaly', models.BooleanField(default=False, verbose_name='نهایی شده')),
                ('statusCode', models.IntegerField(blank=True, null=True, verbose_name='کد وضعیت پرداخت')),
                ('refId', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پیگیری پرداخت')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/%Y/%m/', verbose_name='تصویر رسید')),
                ('codePeygiri', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پیگیری')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'رسید کارت به کارت',
                'verbose_name_plural': 'رسیدهای کارت به کارت',
            },
        ),
    ]
