# Generated by Django 5.2.15 on 2026-09-21 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='order.order'),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='user_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_addresses', to='user.useraddress'),
        ),
        migrations.AddField(
            model_name='ordercoupon',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_coupons', to='product.userdiscountcoupon'),
        ),
        migrations.AddField(
            model_name='ordercoupon',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='order.order'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='order.order'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='pricing_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_details', to='product.pricingtier'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='product.product'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='product.productsale'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='orderdiscount',
            name='order_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='order.orderdetail'),
        ),
        migrations.AddField(
            model_name='orderdiscount',
            name='product_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_discounts', to='product.productdiscount'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.orderstatus'),
        ),
        migrations.AddIndex(
            model_name='paymenttype',
            index=models.Index(fields=['is_active'], name='order_payment_active_idx'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order.paymenttype'),
        ),
        migrations.AddIndex(
            model_name='orderaddress',
            index=models.Index(fields=['user_address'], name='order_addr_user_addr_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercoupon',
            index=models.Index(fields=['order'], name='order_coupon_order_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercoupon',
            index=models.Index(fields=['coupon'], name='order_coupon_coupon_idx'),
        ),
        migrations.AddIndex(
            model_name='ordercoupon',
            index=models.Index(fields=['code'], name='order_coupon_code_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['order'], name='order_detail_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['product'], name='order_detail_product_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdetail',
            index=models.Index(fields=['variant'], name='order_detail_variant_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdiscount',
            index=models.Index(fields=['order_detail'], name='order_discount_detail_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdiscount',
            index=models.Index(fields=['product_discount'], name='order_discount_product_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='order_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='order_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['logistics'], name='order_logistics_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_type'], name='order_payment_type_idx'),
        ),
    ]
