# Generated by Django 5.2.15 on 2026-08-31 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='products/brands/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'product_brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('key', models.SlugField(max_length=150, unique=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('select', 'Select'), ('multi_select', 'Multi Select')], db_index=True, default='text', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'db_table': 'product_features',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SaleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sale Type',
                'verbose_name_plural': 'Sale Types',
                'db_table': 'product_sale_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'product_units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/categories/')),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished')], db_index=True, default='unpublished', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='products/categories/pdf/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='products/categories/videos/')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='product.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'product_categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product.feature')),
            ],
            options={
                'verbose_name': 'Feature Value',
                'verbose_name_plural': 'Feature Values',
                'db_table': 'product_feature_values',
                'ordering': ['sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='CategoryFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_value', models.CharField(blank=True, max_length=500, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.category')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_features', to='product.feature')),
                ('feature_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_features', to='product.featurevalue')),
            ],
            options={
                'verbose_name': 'Category Feature',
                'verbose_name_plural': 'Category Features',
                'db_table': 'product_category_features',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='products/covers/')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished')], db_index=True, default='unpublished', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='products/pdf/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='products/videos/')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.brand')),
                ('categories', models.ManyToManyField(related_name='products', to='product.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_value', models.CharField(blank=True, max_length=500, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_features', to='product.feature')),
                ('feature_values', models.ManyToManyField(blank=True, related_name='product_features', to='product.featurevalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Feature',
                'verbose_name_plural': 'Product Features',
                'db_table': 'product_feature_assignments',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Gallery',
                'verbose_name_plural': 'Product Galleries',
                'db_table': 'product_galleries',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('minimum_quantity', models.PositiveIntegerField(default=1)),
                ('maximum_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Sale',
                'verbose_name_plural': 'Product Sales',
                'db_table': 'product_sales',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField()),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='product.productsale')),
            ],
            options={
                'verbose_name': 'Pricing Tier',
                'verbose_name_plural': 'Pricing Tiers',
                'db_table': 'product_pricing_tiers',
                'ordering': ['min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='product.productsale')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'db_table': 'product_inventory',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'product_variants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productsale',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='product.productvariant'),
        ),
        migrations.AddField(
            model_name='productsale',
            name='sale_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_sales', to='product.saletype'),
        ),
        migrations.AddField(
            model_name='productsale',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_sales', to='product.unit'),
        ),
        migrations.CreateModel(
            name='VariantFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_features', to='product.feature')),
                ('feature_values', models.ManyToManyField(blank=True, related_name='variant_features', to='product.featurevalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.productvariant')),
            ],
            options={
                'verbose_name': 'Variant Feature',
                'verbose_name_plural': 'Variant Features',
                'db_table': 'product_variant_features',
            },
        ),
        migrations.AddConstraint(
            model_name='featurevalue',
            constraint=models.UniqueConstraint(fields=('feature', 'value'), name='unique_feature_value'),
        ),
        migrations.AddConstraint(
            model_name='pricingtier',
            constraint=models.UniqueConstraint(fields=('product_sale', 'min_quantity', 'max_quantity'), name='unique_product_pricing_tier'),
        ),
        migrations.AddConstraint(
            model_name='pricingtier',
            constraint=models.CheckConstraint(condition=models.Q(('min_quantity__gte', 1)), name='tier_min_quantity_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='pricingtier',
            constraint=models.CheckConstraint(condition=models.Q(('max_quantity__isnull', True), ('max_quantity__gte', models.F('min_quantity')), _connector='OR'), name='tier_max_quantity_gte_minimum'),
        ),
        migrations.AddConstraint(
            model_name='pricingtier',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='tier_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_quantity_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.UniqueConstraint(fields=('product', 'variant', 'sale_type', 'unit'), name='unique_product_sale'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__gte', 1)), name='sale_minimum_quantity_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_quantity__isnull', True), ('maximum_quantity__gte', 1), _connector='OR'), name='sale_maximum_quantity_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_quantity__isnull', True), ('maximum_quantity__gte', models.F('minimum_quantity')), _connector='OR'), name='sale_maximum_gte_minimum'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='sale_selling_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__isnull', True), ('purchase_price__gte', 0), _connector='OR'), name='sale_purchase_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='variantfeature',
            constraint=models.UniqueConstraint(fields=('variant', 'feature'), name='unique_variant_feature'),
        ),
    ]
