# Generated by Django 5.2.15 on 2026-09-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='purchase_step',
            field=models.PositiveIntegerField(default=1, help_text='تعداد پله\u200cای که کاربر می\u200cتواند خرید کند (مثلاً 2 یعنی 2، 4، 6، 8، ...)'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_step__gte', 1)), name='sale_purchase_step_gte_one'),
        ),
    ]
