# Generated by Django 5.2.15 on 2026-09-21 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiscountcoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variantfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_features', to='product.feature'),
        ),
        migrations.AddField(
            model_name='variantfeature',
            name='feature_values',
            field=models.ManyToManyField(blank=True, related_name='variant_features', to='product.featurevalue'),
        ),
        migrations.AddField(
            model_name='variantfeature',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='featurevalue',
            constraint=models.UniqueConstraint(fields=('feature', 'value'), name='unique_feature_value'),
        ),
        migrations.AddConstraint(
            model_name='productdiscount',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gt', 0), ('percentage__lte', 100)), name='discount_percentage_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='pricingtier',
            constraint=models.UniqueConstraint(fields=('product_sale', 'min_quantity', 'max_quantity'), name='unique_product_pricing_tier'),
        ),
        migrations.AddConstraint(
            model_name='pricingtier',
            constraint=models.CheckConstraint(condition=models.Q(('min_quantity__gte', 1)), name='tier_min_quantity_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='pricingtier',
            constraint=models.CheckConstraint(condition=models.Q(('max_quantity__isnull', True), ('max_quantity__gte', models.F('min_quantity')), _connector='OR'), name='tier_max_quantity_gte_minimum'),
        ),
        migrations.AddConstraint(
            model_name='pricingtier',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='tier_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_quantity_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.UniqueConstraint(fields=('product', 'variant', 'sale_type', 'unit'), name='unique_product_sale'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__gte', 1)), name='sale_minimum_quantity_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_quantity__isnull', True), ('maximum_quantity__gte', 1), _connector='OR'), name='sale_maximum_quantity_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_quantity__isnull', True), ('maximum_quantity__gte', models.F('minimum_quantity')), _connector='OR'), name='sale_maximum_gte_minimum'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='sale_selling_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__isnull', True), ('purchase_price__gte', 0), _connector='OR'), name='sale_purchase_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='productsale',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_step__gte', 1)), name='sale_purchase_step_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='userdiscountcoupon',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gt', 0), ('percentage__lte', 100)), name='coupon_percentage_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='variantfeature',
            constraint=models.UniqueConstraint(fields=('variant', 'feature'), name='unique_variant_feature'),
        ),
    ]
