# Generated by Django 5.2.15 on 2026-09-14 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productsale_purchase_step_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='discounts', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Discount',
                'verbose_name_plural': 'Product Discounts',
                'db_table': 'product_discounts',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('percentage__gt', 0), ('percentage__lte', 100)), name='discount_percentage_between_0_and_100')],
            },
        ),
        migrations.CreateModel(
            name='UserDiscountCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Discount Coupon',
                'verbose_name_plural': 'User Discount Coupons',
                'db_table': 'user_discount_coupons',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('percentage__gt', 0), ('percentage__lte', 100)), name='coupon_percentage_between_0_and_100')],
            },
        ),
    ]
